[package]
name = "aoc2019"
version = "0.1.0"
authors = ["John Ledbetter <john.ledbetter@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "*"
num-derive = "*"
itertools = "*"
regex = "*"
lazy_static = "*"
nom = "*"